<?php

namespace ContainerNQwPe5W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wc4srRPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wc4srRP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wc4srRP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'horaireRepository' => ['privates', 'App\\Repository\\HoraireRepository', 'getHoraireRepositoryService', false],
        ], [
            'horaireRepository' => 'App\\Repository\\HoraireRepository',
        ]);
    }
}
