<?php

namespace ContainerNQwPe5W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CCBhVhT.App\Controller\EmployeeController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CCBhVhT.App\\Controller\\EmployeeController::delete()'] = ($container->privates['.service_locator.CCBhVhT'] ?? $container->load('get_ServiceLocator_CCBhVhTService'))->withContext('App\\Controller\\EmployeeController::delete()', $container);
    }
}
