<?php

namespace ContainerNQwPe5W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagesControlleraccueilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M1tMNMd.App\Controller\PagesController::accueil()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M1tMNMd.App\\Controller\\PagesController::accueil()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'animalRepository' => ['privates', 'App\\Repository\\AnimalRepository', 'getAnimalRepositoryService', true],
            'habitatRepository' => ['privates', 'App\\Repository\\HabitatRepository', 'getHabitatRepositoryService', true],
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
        ], [
            'entityManager' => '?',
            'animalRepository' => 'App\\Repository\\AnimalRepository',
            'habitatRepository' => 'App\\Repository\\HabitatRepository',
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
            'avisRepository' => 'App\\Repository\\AvisRepository',
        ]))->withContext('App\\Controller\\PagesController::accueil()', $container);
    }
}
