<?php

namespace ContainerNQwPe5W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagesControlleranimalVisiteurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JKWArK..App\Controller\PagesController::animalVisiteur()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JKWArK..App\\Controller\\PagesController::animalVisiteur()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animalRepository' => ['privates', 'App\\Repository\\AnimalRepository', 'getAnimalRepositoryService', true],
            'habitatRepository' => ['privates', 'App\\Repository\\HabitatRepository', 'getHabitatRepositoryService', true],
            'veterinaireRepository' => ['privates', 'App\\Repository\\VeterinaireRepository', 'getVeterinaireRepositoryService', true],
        ], [
            'animalRepository' => 'App\\Repository\\AnimalRepository',
            'habitatRepository' => 'App\\Repository\\HabitatRepository',
            'veterinaireRepository' => 'App\\Repository\\VeterinaireRepository',
        ]))->withContext('App\\Controller\\PagesController::animalVisiteur()', $container);
    }
}
