<?php

namespace ContainerNQwPe5W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagesControllerhabitatVisiteurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O5x8RWD.App\Controller\PagesController::habitatVisiteur()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O5x8RWD.App\\Controller\\PagesController::habitatVisiteur()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'habitatRepository' => ['privates', 'App\\Repository\\HabitatRepository', 'getHabitatRepositoryService', true],
            'animalRepository' => ['privates', 'App\\Repository\\AnimalRepository', 'getAnimalRepositoryService', true],
        ], [
            'habitatRepository' => 'App\\Repository\\HabitatRepository',
            'animalRepository' => 'App\\Repository\\AnimalRepository',
        ]))->withContext('App\\Controller\\PagesController::habitatVisiteur()', $container);
    }
}
