<?php

namespace ContainerNQwPe5W;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r0.xc1L.App\Controller\UtilisateurController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r0.xc1L.App\\Controller\\UtilisateurController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'mailerService' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
        ], [
            'passwordHasher' => '?',
            'mailerService' => 'App\\Service\\MailerService',
        ]))->withContext('App\\Controller\\UtilisateurController::new()', $container);
    }
}
