framework:
    cache:
        pools:
            app.cache.redis:
                adapter: cache.redis
                provider: '%env(UPSTASH_REDIS_REST_URL)%'
                default_lifetime: 3600
