framework:
    http_method_override: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id: 'session.handler.redis'
        save_path: '%env(UPSTASH_REDIS_URL)%'  # Utilisation de Redis via l'URL de l'environnement
    profiler:
        enabled: true
        collect: true
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(UPSTASH_REDIS_URL)%'  # Utilisation de Redis pour le cache
        system: cache.adapter.system
        pools:
            app.cache:
                adapter: cache.adapter.redis
                default_lifetime: 3600
    assets:
        base_path: '/public'
    asset_mapper:
        paths:
            - '%kernel.project_dir%/public'
