framework:
    http_method_override: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id: snc_redis.session.handler
        cookie_lifetime: 3600
        save_path: '%env(REDIS_URL)%'  # Utilisation de Redis via l'URL de l'environnement
    profiler:
        only_exceptions: false
        enabled: false  # Désactiver en production
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'  # Utilisation de Redis pour le cache
        system: cache.adapter.system
        pools:
            app.cache:
                adapter: cache.adapter.redis
                default_lifetime: 3600
    assets:
        base_path: '/styles'
    asset_mapper:
        paths:
            - '%kernel.project_dir%/public/styles'
