framework:
    cache:
        pools:
            redis:
                adapter: cache.adapter.redis
                default_lifetime: 3600
                provider: 'redis://%env(REDIS_URL)%'
                # Vous pouvez également ajouter d'autres options ici comme `prefix` ou `timeout`
