snc_redis:
    clients:
        redis:
            type: 'predis'  # Utilisation de Predis
            alias: default
            dsn: '%env(REDIS_URL)%'  # Utilisation de l'URL de l'environnement
            options:
                connection_timeout: 5  # Timeout pour la connexion
                read_write_timeout: 5  # Timeout pour la lecture/écriture
