snc_redis:
    clients:
        default:
            type: predis 
            alias: redis
            dsn: "%env(REDIS_URL)%"

    monolog:
        client: redis
        formatter: 'monolog.formatter.json'
        key: 'monolog:logs'
