version: '3.8'

services:
  ### --- Serveur Web avec PHP ---
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - mongodb
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@mysql:3306/symfony?serverVersion=8.0
      MONGODB_URL: mongodb://mongodb:27017
    ports:
      - "8000:8000"

  ### --- Base de données MySQL ---
  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ### --- Base de données MongoDB ---
  mongodb:
    image: mongo:6.0
    container_name: symfony_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  ### --- Interface d'administration pour MongoDB (Mongo Express) ---
  mongo-express:
    image: mongo-express
    container_name: symfony_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"

volumes:
  mysql_data:
  mongodb_data:
