<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UVsSjDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u_VsSjD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u_VsSjD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avis' => ['privates', '.errored..service_locator.u_VsSjD.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.u_VsSjD": it needs an instance of "App\\Entity\\Avis" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'avis' => 'App\\Entity\\Avis',
            'entityManager' => '?',
        ]);
    }
}
