<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvis2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u_VsSjD.App\Entity\Avis' shared service.
     *
     * @return \App\Entity\Avis
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.u_VsSjD": it needs an instance of "App\\Entity\\Avis" but this type has been excluded in "config/services.yaml".');
    }
}
