<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DashboardController' shared autowired service.
     *
     * @return \App\Controller\DashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'DashboardController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PredisService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'predis'.\DIRECTORY_SEPARATOR.'predis'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'predis'.\DIRECTORY_SEPARATOR.'predis'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Client.php';

        $container->services['App\\Controller\\DashboardController'] = $instance = new \App\Controller\DashboardController(($container->privates['App\\Repository\\VeterinaireRepository'] ?? $container->load('getVeterinaireRepositoryService')), ($container->privates['App\\Repository\\ConsultationRepository'] ?? $container->load('getConsultationRepositoryService')), ($container->privates['App\\Repository\\AnimalRepository'] ?? $container->load('getAnimalRepositoryService')), ($container->privates['App\\Repository\\EmployeeRepository'] ?? $container->load('getEmployeeRepositoryService')), ($container->privates['App\\Repository\\CommentaireRepository'] ?? $container->load('getCommentaireRepositoryService')), new \App\Service\PredisService(new \Predis\Client($container->getEnv('REDIS_DSN'))));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\DashboardController', $container));

        return $instance;
    }
}
