<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uez5N1E.App\Controller\EmployeeController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uez5N1E.App\\Controller\\EmployeeController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employee' => ['privates', '.errored..service_locator.uez5N1E.App\\Entity\\Employee', NULL, 'Cannot autowire service ".service_locator.uez5N1E": it needs an instance of "App\\Entity\\Employee" but this type has been excluded in "config/services.yaml".'],
        ], [
            'employee' => 'App\\Entity\\Employee',
        ]))->withContext('App\\Controller\\EmployeeController::show()', $container);
    }
}
