<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageUploadServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ImageUploadService' shared autowired service.
     *
     * @return \App\Service\ImageUploadService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'ImageUploadService.php';

        return $container->privates['App\\Service\\ImageUploadService'] = new \App\Service\ImageUploadService(['animaux' => $container->getEnv('ANIMAUX_IMAGES_DIRECTORY'), 'habitats' => $container->getEnv('HABITATS_IMAGES_DIRECTORY'), 'services' => $container->getEnv('SERVICES_IMAGES_DIRECTORY')]);
    }
}
