<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M4HqexZ.App\Controller\UtilisateurController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M4HqexZ.App\\Controller\\UtilisateurController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateur' => ['privates', '.errored..service_locator.M4HqexZ.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.M4HqexZ": it needs an instance of "App\\Entity\\Utilisateur" but this type has been excluded in "config/services.yaml".'],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'utilisateur' => 'App\\Entity\\Utilisateur',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\UtilisateurController::edit()', $container);
    }
}
