<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeterinaireRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\VeterinaireRepository' shared autowired service.
     *
     * @return \App\Repository\VeterinaireRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'VeterinaireRepository.php';

        return $container->privates['App\\Repository\\VeterinaireRepository'] = new \App\Repository\VeterinaireRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
