<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeterinaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2P_KNB6.App\Entity\Veterinaire' shared service.
     *
     * @return \App\Entity\Veterinaire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2P_KNB6": it needs an instance of "App\\Entity\\Veterinaire" but this type has been excluded in "config/services.yaml".');
    }
}
