<?php

namespace ContainerZVKftOG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeterinaireControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2P_KNB6.App\Controller\VeterinaireController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2P_KNB6.App\\Controller\\VeterinaireController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'veterinaire' => ['privates', '.errored..service_locator.2P_KNB6.App\\Entity\\Veterinaire', NULL, 'Cannot autowire service ".service_locator.2P_KNB6": it needs an instance of "App\\Entity\\Veterinaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'veterinaire' => 'App\\Entity\\Veterinaire',
        ]))->withContext('App\\Controller\\VeterinaireController::delete()', $container);
    }
}
