<<<<<<< HEAD
parameters:
    animaux_images_directory: '%env(ANIMAUX_IMAGES_DIRECTORY)%'
    habitats_images_directory: '%env(HABITATS_IMAGES_DIRECTORY)%'
    services_images_directory: '%env(SERVICES_IMAGES_DIRECTORY)%'

services:
    _defaults:
        autowire: true      # Active l'autowiring pour toutes les classes
        autoconfigure: true # Active la configuration automatique des services
        public: false       # Par défaut, les services ne sont pas publics

    # Rendre les classes de src/ disponibles en tant que services
    App\:
        resource: '../src/'  # Déclare le répertoire src/ comme ressource
=======
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
>>>>>>> 82979460f8a084802515ce4ce31cbaac6128233c
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
<<<<<<< HEAD
            - '../src/{Entity,Migrations,Tests}'

    # Configuration explicite pour les contrôleurs
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Configuration explicite pour l'extension Twig HeaderFooterExtension
    App\Twig\HeaderFooterExtension:
        arguments:
            $horaireRepository: '@App\Repository\HoraireRepository'
        tags: ['twig.extension']

    # Service pour la gestion des uploads d'images
    App\Service\ImageUploadService:
        arguments:
            $directories:
                animaux: '%animaux_images_directory%'
                habitats: '%habitats_images_directory%'
                services: '%services_images_directory%'

    # Configuration pour Redis (si vous utilisez snc/redis-bundle, ne le redéfinissez pas ici)
    snc_redis.session.handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@snc_redis.client'  # Le client Redis configuré

    # Client Redis (avec DSN)
    Predis\Client:
        class: Predis\Client
        arguments:
            - '%env(REDIS_DSN)%'

    # Définition du service PredisService
    App\Service\PredisService:
        arguments:
            $redis: '@Predis\Client'

    App\Service\MailerService:
        arguments:
            $mailer: '@mailer.mailer' # Injecte le MailerInterface automatiquement
=======

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
>>>>>>> 82979460f8a084802515ce4ce31cbaac6128233c
