<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFGPIJbv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFGPIJbv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFGPIJbv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFGPIJbv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFGPIJbv\App_KernelDevDebugContainer([
    'container.build_hash' => 'FGPIJbv',
    'container.build_id' => '22700f9f',
    'container.build_time' => 1737465806,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFGPIJbv');
