<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxgpPvW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxgpPvW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxgpPvW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxgpPvW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxgpPvW\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxgpPvW',
    'container.build_id' => '21d46bb7',
    'container.build_time' => 1737912224,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxgpPvW');
