<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEquM9YX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEquM9YX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEquM9YX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEquM9YX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEquM9YX\App_KernelDevDebugContainer([
    'container.build_hash' => 'EquM9YX',
    'container.build_id' => '5eb4c4c5',
    'container.build_time' => 1737915621,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEquM9YX');
